columnSuffix: null
contentColumnType: string
fieldGroup: dbe6ebbf-dc13-4c09-9138-4bce03eae149 # Common
handle: backgroundImage
instructions: ''
name: 'Background Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:a8a78f49-c726-40f4-b9e8-a9441e1428eb' # uploads
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Add a Background Image'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:a8a78f49-c726-40f4-b9e8-a9441e1428eb' # uploads
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:a8a78f49-c726-40f4-b9e8-a9441e1428eb' # uploads
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
