columnSuffix: null
contentColumnType: string
fieldGroup: dbe6ebbf-dc13-4c09-9138-4bce03eae149 # Common
handle: gameEntries
instructions: 'Fill out the entry with the informations about the game'
name: 'Game Entries'
searchable: false
settings:
  contentTable: '{{%matrixcontent_gameentries}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
