defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  1e0206b6-0cf7-4792-bb36-277a588e8fac: # Upcominggames
    enabledByDefault: true
    hasUrls: true
    template: home
    uriFormat: __home__
type: single
